### ISSUE TITLE
installation example

### ISSUE THREAD

**Issue by francescoagati** [len/Cuis-Smalltalk-DWM#1]
How to install it?  i vae put inside the image but i dont'know how activate it

**Comment by len** [comment]
Hi,
To activate it you must select the DWMTheme. From the world menu:
Preferences -> Themes -> DWMTheme. Then close all windows, and if you want
you can change the world color to black by getting the halos on the world,
inspecting it (from the debug halo) and doing "self color: Color black".
Also, in the screenshots I'm using the DejaVu Mono font, that you can
install from the AdditionalFonts/ directory if you want. The default font
in the image is 'DejaVu Sans' and the current version of that font has some
artifacts when using black background (some green shadow), if that bothers
you, you can get rid of it by doing "Preferences disable:
#subPixelRenderColorFonts".

But wait. I just tested it and there are some problems because I forgot to
commit some changes I made related to syntax highliting. I'll fix this
tonight and get back to you.

**Comment by len** [comment]
Ok, please get the latest version from github, it should work fine now. Let
me know if you have any problem.

On Thu, Jun 23, 2016 at 10:48 PM, Luciano Notarfrancesco <luchiano@gmail.com

**Comment by francescoagati** [comment]
hi,
thanks for fast reply :-). downloaded last versions and works all good.
really thanks :-)
Francesco
